#!/bin/bash

NAME="coreprotocols_app"                                 # Name of the application
DJANGODIR=/opt/django-prod/coreprotocols/
SOCKFILE=/opt/django-prod/coreprotocols/run/gunicorn.sock  # we will communicate using this unix socket
USER=user                                                # the user to run as
GROUP=devops                                             # the group to run as
NUM_WORKERS=5                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=coreprotocols.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=coreprotocols.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE \
  --pid=/opt/django-prod/coreprotocols/run/gunicorn.pid \
  --backlog=1024 \
  --worker-connections=2000 \
  --daemon