# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamspirit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Estimation Session', max_length=100),
            preserve_default=False,
        ),
    ]
